language: ruby
rvm: 2.1.0
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish'

env:
  global:
    - GIT_COMMITTER_NAME="syon"
    - GIT_COMMITTER_EMAIL="syon.xiii@gmail.com"
    - GIT_AUTHOR_NAME="syon"
    - GIT_AUTHOR_EMAIL="syon.xiii@gmail.com"
    - secure: "g2S8D4vldZPqsFLpFRDu8+3xNotChlOEjsXSQvjuFHC/N5HvKOM4weSYxcLvalfSGaspZKWSqw8ZOF9NeeZV7DdywdOlRN1+xwGfuqPO6OnFIUKjT3n9YAXF6Ar+ihDTE7PB+vYM70+MaDDBoEfX+mTz8D7c6+VS7uPSdKAOwTM="
